### PR TITLE
Fixes Google JWT token not being refreshed when tab hidden

### LINKED ISSUE #93: Client JWT token not being refreshed
The client JWT token is not being refreshed by the Google JS lib in certain scenarios specifically when the client is hidden or not the active tab!

Looks like we need a different approach until they fix this. It may be that we can use:

https://developers.google.com/identity/sign-in/web/reference#googleuserreloadauthresponse

so, we would start a timer when the JWT token is first created and then after 45 mins call `reloadAuthResponse` ? worth a try.

https://www.fullstackreact.com/articles/introduction-to-web-workers-with-react/

### PR DESCRIPTION
**Pull request by whomwah**
When the user signs via google a token is send back. This is a short lived token (60 mins). We use this token to authenticate requests to the API. The Google JS lib handles refreshing the token so it never expires but they use `setTimeout` to do this. When a browser tab is not in focus the browser suspends timeouts (so they don't use unnecessary resource). This means you have a situation where the token would not get updated and the user would have to wait for a failure before having to refresh their page. Not a great UX.

This PR adds our own refresh using background workers. Background workers don't suffer the same suspend issue. When we get a new token we add a background timer for 45 mins and then refresh the token then.

Fixes #93

### CODE REVIEW

File: frontend/src/utils/signin-token/index.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
+import * as workerTimers from 'worker-timers'
+
+const checkForTokenInMilliseconds = 2700000
+
+const SignInToken = {
+  refresh: (googleApi, success) => {
```
Comment (tomajwinter) [inline frontend/src/utils/signin-token/index.js]: Not a blocker but you as you mentioned, you _could_ have this return a promise and avoid the success callback

File: frontend/src/utils/signin-token/index.js [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+    return workerTimers.setTimeout(() => {
+      googleApi.reloadAuthResponse().then(
+        (response) => success(response.id_token),
+        (err) => console.warn('Token un-refreshable: ', err.message))
```
Comment (tomajwinter) [inline frontend/src/utils/signin-token/index.js]: Is there any merit in sending this message to the logger? Or is this an expected thing that might happen often enough it'd be noisy?

File: frontend/src/utils/signin-token/index.spec.js [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+})
+
+describe('SignInToken', () => {
+  beforeEach(() => {
+    jest.clearAllMocks()
+  })
+
+  describe('.refresh', () => {
+    it('returns a token', done => {
+      expect.assertions(2)
```
Comment (tomajwinter) [inline frontend/src/utils/signin-token/index.spec.js]: Nice 👍 - this is a really clear test for the async behaviour

File: frontend/src/utils/signin-token/index.js (hunk 1 above)
Comment (whomwah) [reply frontend/src/utils/signin-token/index.js]: Yeah, I think I will make that change.

File: frontend/src/utils/signin-token/index.js (hunk 2 above)
Comment (whomwah) [reply frontend/src/utils/signin-token/index.js]: This is the frontend so the logger is not available.

Comment (tomajwinter) [reply frontend/src/utils/signin-token/index.js]: Oh yeah, sorry! 🤦‍♂
